kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    username: isundaylee
    password:
      from_secret: docker-hub-password
    repo: isundaylee/short_url
    tags: latest
