version: '3'
services:
  web:
    build: .
    ports:
      - 9292:9292
    volumes:
      - ".:/usr/src/app"
    command: bundle exec rackup -p9292 --host 0.0.0.0
    environment:
      - MBTA_API_KEY
